package sql

import (
	"fmt"
	"path"
	"strings"

	"github.com/dlclark/regexp2"
	"github.com/go-gorp/gorp/v3"
	"github.com/semaphoreui/semaphore/db"
	log "github.com/sirupsen/logrus"
)

var (
	autoIncrementRE        = regexp2.MustCompile(`\bautoincrement\b`, regexp2.IgnoreCase|regexp2.Multiline)
	serialRE               = regexp2.MustCompile(`\bint(?:eger)* primary key autoincrement\b`, regexp2.IgnoreCase|regexp2.Multiline)
	dateTimeTypeRE         = regexp2.MustCompile(`\bdatetime\b`, regexp2.IgnoreCase|regexp2.Multiline)
	tinyintRE              = regexp2.MustCompile(`\btinyint\b`, regexp2.IgnoreCase|regexp2.Multiline)
	numberRE               = regexp2.MustCompile(`\b(?:big)?int(?:eger)?\b`, regexp2.IgnoreCase|regexp2.Multiline)
	booleanRE              = regexp2.MustCompile(`\bbool(?:ean)*\b`, regexp2.IgnoreCase|regexp2.Multiline)
	falseRE                = regexp2.MustCompile(`\bfalse\b`, regexp2.IgnoreCase|regexp2.Multiline)
	trueRE                 = regexp2.MustCompile(`\btrue\b`, regexp2.IgnoreCase|regexp2.Multiline)
	longtextRE             = regexp2.MustCompile(`\b(long)*text\b`, regexp2.IgnoreCase|regexp2.Multiline)
	ifExistsRE             = regexp2.MustCompile(`\bif exists\b`, regexp2.IgnoreCase|regexp2.Multiline)
	changeRE               = regexp2.MustCompile(`^alter table "(\w+)" change "(\w+)" "(\w+)" ([\w\(\)]+)( autoincrement)?( not null)?$`, regexp2.IgnoreCase|regexp2.Multiline)
	columnRE               = regexp2.MustCompile(`\b(add|modify) column\b`, regexp2.IgnoreCase|regexp2.Multiline)
	tableNameRE            = regexp2.MustCompile(`\b((?:create|alter|drop)\s+(?:table|index\s+\x60?\w+\x60?\s+on)|from|join|into|update|delete\s+from|references)\s+(\x60?\x22?)([a-z_][a-z0-9_]*)\2`, regexp2.IgnoreCase|regexp2.Multiline)
	quotedWordsRE          = regexp2.MustCompile(`\x60(\b\w+\b)\x60`, regexp2.IgnoreCase|regexp2.Multiline)
	dropForeignKeyRE       = regexp2.MustCompile(`\bdrop foreign key\b`, regexp2.IgnoreCase|regexp2.Multiline)
	implicitBooleanCheckRE = regexp2.MustCompile(`\bWHERE\s+\x60([a-z_][a-z0-9_]*)\x60(\s*(;|\z))`, regexp2.IgnoreCase|regexp2.Multiline)
	nonPrintableRE         = regexp2.MustCompile(`[\r\n\t]+`, regexp2.IgnoreCase|regexp2.Multiline)
	semicoloumnRE          = regexp2.MustCompile(";", regexp2.Multiline)
	datatypeWithDefaultRE  = regexp2.MustCompile(`(NOT\s+NULL|NULL)\s+(DEFAULT\s+(?:'[^']*'|[^\s,()]+))|(DEFAULT\s+(?:'[^']*'|[^\s,()]+))\s+(NOT\s+NULL|NULL)`, regexp2.IgnoreCase|regexp2.Multiline)
)

// getVersionPath is the humanoid version with the file format appended
func getVersionPath(version db.Migration) string {
	return version.HumanoidVersion() + ".sql"
}

// getVersionErrPath is the humanoid version with '.err' and file format appended
func getVersionErrPath(version db.Migration) string {
	return version.HumanoidVersion() + ".err.sql"
}

// getVersionSQL takes a path to an SQL file and returns it from embed.FS
// a slice of strings separated by newlines
func getVersionSQL(name string) (queries []string) {
	sql, err := dbAssets.ReadFile(path.Join("migrations", name))
	if err != nil {
		panic(err)
	}
	queries = strings.Split(strings.ReplaceAll(string(sql), ";\r\n", ";\n"), ";\n")
	for i := range queries {
		queries[i] = strings.Trim(queries[i], "\r\n\t ")
	}
	return
}

// prepareMigration converts migration SQLite-query to current dialect.
// Supported MySQL and Postgres dialects.
func (d *SqlDb) prepareMigration(query string) []string {
	query, _ = nonPrintableRE.Replace(query, " ", -1, -1)
	var queries []string

	switch dialect := d.sql.Dialect.(type) {
	case gorp.MySQLDialect:
		queries = append(queries, prepareMySQLMigration(query))
	case gorp.OracleDialect:
		queries = append(queries, prepareOracleMigration(query)...)
	case gorp.PostgresDialect:
		queries = append(queries, preparePostgresMigration(query)...)
	default:
		log.Warnf("Unsupported SQL dialect: %T", dialect)
	}

	return queries
}

func prepareMySQLMigration(query string) string {
	query, _ = autoIncrementRE.Replace(query, "auto_increment", -1, -1)
	query, _ = ifExistsRE.Replace(query, "", -1, -1)
	return query
}

func prepareOracleMigration(query string) []string {
	var queries []string
	query, _ = semicoloumnRE.Replace(query, "", -1, -1)

	// Handle "if exists" logic
	if m, _ := ifExistsRE.FindStringMatch(query); m != nil {
		query, _ = ifExistsRE.Replace(query, "", -1, -1)
		query = strings.TrimSpace(query)
		query = "begin execute immediate '" + query + "'; exception when others then null; end;"
	}

	// Replace common patterns
	query = replacePatterns(query, map[*regexp2.Regexp]string{
		trueRE:                 "1",
		falseRE:                "0",
		datatypeWithDefaultRE:  "${2} ${1}",
		dateTimeTypeRE:         "timestamp",
		columnRE:               "${1}",
		longtextRE:             "clob",
		serialRE:               "number generated by default as identity primary key",
		booleanRE:              "number(1,0)",
		tinyintRE:              "number(5)",
		numberRE:               "number",
		dropForeignKeyRE:       "drop constraint",
		implicitBooleanCheckRE: "where \x60${1}\x60 = 1",
	})

	// Handle table name quoting
	query = processTableNames(query)

	// Handle quoted words
	query = processQuotedWords(query)

	// Handle column changes
	queries = append(queries, processColumnChanges(query)...)

	return queries
}

func preparePostgresMigration(query string) []string {
	var queries []string

	// Handle column changes
	if m, _ := changeRE.FindStringMatch(query); m != nil {
		grps := m.Groups()
		tableName := strings.ToUpper(grps[1].Captures[0].String())
		oldColumnName := strings.ToUpper(grps[2].Captures[0].String())
		newColumnName := strings.ToUpper(grps[3].Captures[0].String())
		columnType := grps[4].Captures[0].String()
		columnNotNull := len(grps[6].Captures) > 0 && grps[6].Captures[0].String() != ""

		queries = append(queries, fmt.Sprintf("alter table `%s` alter column `%s` type %s", tableName, oldColumnName, columnType))

		if columnNotNull {
			queries = append(queries, fmt.Sprintf("alter table `%s` alter column `%s` set not null", tableName, oldColumnName))
		} else {
			queries = append(queries, fmt.Sprintf("alter table `%s` alter column `%s` drop not null", tableName, oldColumnName))
		}

		if oldColumnName != newColumnName {
			queries = append(queries, fmt.Sprintf("alter table `%s` rename column `%s` to `%s`", tableName, oldColumnName, newColumnName))
		}
	}

	// Replace common patterns
	query = replacePatterns(query, map[*regexp2.Regexp]string{
		dateTimeTypeRE:    "timestamp",
		tinyintRE:         "smallint",
		longtextRE:        "text",
		serialRE:          "serial primary key",
		dropForeignKeyRE:  "drop constraint",
		identifierQuoteRE: "\"",
	})

	queries = append(queries, query)
	return queries
}

func replacePatterns(query string, patterns map[*regexp2.Regexp]string) string {
	for re, replacement := range patterns {
		query, _ = re.Replace(query, replacement, -1, -1)
	}
	return query
}

func processTableNames(query string) string {
	match, err := tableNameRE.FindStringMatch(query)
	sb := strings.Builder{}
	pos := 0

	for match != nil && err == nil {
		sb.WriteString(query[pos:match.Index])

		keyword := match.GroupByNumber(1).String()
		tableName := strings.ToUpper(match.GroupByNumber(3).String())

		// Preserve keyword, add quoted table name
		sb.WriteString(keyword + ` "` + tableName + `"`)

		pos = match.Index + match.Length
		match, err = tableNameRE.FindNextMatch(match)
	}
	sb.WriteString(query[pos:])
	return sb.String()
}

func processQuotedWords(query string) string {
	match, err := quotedWordsRE.FindStringMatch(query)
	sb := strings.Builder{}
	pos := 0

	for match != nil && err == nil {
		sb.WriteString(query[pos:match.Index])

		wordToQuote := match.GroupByNumber(1).String()
		sb.WriteString(`"` + strings.ToUpper(wordToQuote) + `"`)

		pos = match.Index + match.Length
		match, err = quotedWordsRE.FindNextMatch(match)
	}
	sb.WriteString(query[pos:])
	return sb.String()
}

func processColumnChanges(query string) []string {
	var queries []string
	if m, _ := changeRE.FindStringMatch(query); m != nil {
		grps := m.Groups()
		tableName := strings.ToUpper(grps[1].Captures[0].String())
		oldColumnName := strings.ToUpper(grps[2].Captures[0].String())
		newColumnName := strings.ToUpper(grps[3].Captures[0].String())
		columnType := grps[4].Captures[0].String()
		columnNotNull := len(grps[6].Captures) > 0 && grps[6].Captures[0].String() != ""

		queries = append(queries, fmt.Sprintf("alter table \"%s\" modify \"%s\" %s", tableName, oldColumnName, columnType))
		if columnNotNull {
			queries = append(queries, fmt.Sprintf("begin execute immediate 'alter table \"%s\" modify \"%s\" not null'; exception when others then null; end;", tableName, oldColumnName))
		}

		if oldColumnName != newColumnName {
			queries = append(queries, fmt.Sprintf("alter table \"%s\" rename column \"%s\" to \"%s\"", tableName, oldColumnName, newColumnName))
		}
	} else {
		queries = append(queries, query)
	}
	return queries
}
